# Generated by Django 5.2.6 on 2026-03-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[('Herr', 'Herr'), ('Frau', 'Frau')], max_length=10)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('street', models.CharField(max_length=200)),
                ('houseNumber', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('houseConsumption', models.IntegerField()),
                ('heatingConsumption', models.IntegerField(blank=True, null=True)),
                ('heatingInfo', models.TextField(blank=True)),
                ('objectDetails', models.TextField(blank=True)),
                ('priority', models.CharField(max_length=200)),
                ('extraOptions', models.JSONField(blank=True, default=list)),
                ('required_file', models.FileField(upload_to='leads/')),
                ('optional_file', models.FileField(blank=True, null=True, upload_to='leads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
