# Generated by Django 5.2.6 on 2026-03-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_extraoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='extraOptions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
