# Generated by Django 5.2.6 on 2026-03-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_extraoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='required_file',
            field=models.FileField(blank=True, null=True, upload_to='leads/'),
        ),
    ]
